### ISSUE TITLE
redis-server enters an unresponsive state while running inference workflow

### ISSUE THREAD

**Issue by filipecosta90** [RedisAI/RedisAI#222]
Considering we run RedisAI via
```
docker run -p 6379:6379 redisai/redisai:edge
```
And we do the following steps:
## 0.1 )getting the dataset

```
wget https://performance-cto-group-public.s3.amazonaws.com/benchmarks/redisai/aibench/models/tensorflow/creditcardfraud.pb  
 wget https://performance-cto-group-public.s3.amazonaws.com/benchmarks/redisai/aibench/gz/aibench_generate_data-creditcard-fraud.dat.gz
cat aibench_generate_data-creditcard-fraud.dat.gz | gunzip > aibench_generate_data-creditcard-fraud.dat
```

## 0.2 )loading the model to redis-server 
```
redis-cli -x AI.MODELSET financialNet \
            TF CPU INPUTS transaction reference \
            OUTPUTS output < creditcardfraud.pb
```

## 0.3 )loading the reference data
```
$ docker run -it -v ~/aibench_generate_data-creditcard-fraud.dat:/tmp/aibench_generate_data-creditcard-fraud.dat --network host  filipecosta90/aibench:edge aibench_load_data -reporting-period 1000ms -workers 8 -pipeline 100 -file /tmp/aibench_generate_data-creditcard-fraud.dat
-------------------------
 aibench - Docker Image  
-------------------------
Checking if request binary aibench_load_data exists
time (ns),total commands,instantaneous commands/s,overall commands/s
1568805100512833500,323972,323811.94,323811.94
1568805101518874600,569614,244167.01,283879.40
1568805102518941700,569614,0.00,189454.39
1568805103512859100,569614,0.00,142385.00
1568805104512886900,569614,0.00,113910.30
1568805105478875900,569614,0.00,94926.69
1568805106478826000,569614,0.00,81367.41
1568805107478880000,569614,0.00,71196.65
1568805108478848500,569614,0.00,63286.65
Took:    9.146 sec

...done.
```

## 1 ) running the inference ( UNRESPONSIVE )
```
$ docker run -it -v ~/aibench_generate_data-creditcard-fraud.dat:/tmp/aibench_generate_data-creditcard-fraud.dat --network host  filipecosta90/aibench:edge aibench_run_inference_redisai  -print-interval 0 -reporting-period 1000ms -workers 8 -burn-in 10 -max-queries 0 -file /tmp/aibench_generate_data-creditcard-fraud.dat -model financialNet
-------------------------
 aibench - Docker Image  
-------------------------
Checking if request binary aibench_run_inference_redisai exists
time (ns),total inferences,instantaneous inferences/s,overall inferences/s
burn-in complete after 10 queries with 8 workers
1568805167613297900,2064,2039.44,2039.44
1568805168613285800,4824,2760.03,2397.57
1568805169613363200,7444,2619.80,2471.36
1568805170617747400,8183,735.77,2037.35
1568805171613418000,8183,0.00,1632.63
1568805172613637100,8183,0.00,1361.02
1568805173617737400,8183,0.00,1166.25
1568805174613739800,8183,0.00,1021.28
1568805175616599100,8183,0.00,907.67
1568805176615028000,8183,0.00,817.17
1568805177613696500,8183,0.00,743.07
```

**Comment by filipecosta90** [comment]
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
__lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
103	../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.
(gdb) info threads
  Id   Target Id                                     Frame 
* 1    Thread 0x7fa6eb593f80 (LWP 1) "redis-server"  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
  2    Thread 0x7fa6eabff700 (LWP 15) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a7572e6dc8 <bio_newjob_cond+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7fa6ea3fe700 (LWP 16) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a7572e6df8 <bio_newjob_cond+88>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  4    Thread 0x7fa6e9bfd700 (LWP 17) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a7572e6e28 <bio_newjob_cond+136>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  5    Thread 0x7fa6de8ab700 (LWP 18) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a758635b58) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  6    Thread 0x7fa6de0aa700 (LWP 19) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a757ed18d8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  7    Thread 0x7fa6dd8a9700 (LWP 20) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a757ed1958) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  8    Thread 0x7fa6dd0a8700 (LWP 21) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a757ed19d8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  9    Thread 0x7fa6dc8a7700 (LWP 22) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a757ed1a58) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  10   Thread 0x7fa6d7fff700 (LWP 23) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a757ed1ad8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  11   Thread 0x7fa6d77fe700 (LWP 24) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a757ed1b58) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  12   Thread 0x7fa6d6ffd700 (LWP 25) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a75865c4d8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  13   Thread 0x7fa6d5ffb700 (LWP 27) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x7fa6b00050d8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  14   Thread 0x7fa6d67fc700 (LWP 28) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a7587968d8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  15   Thread 0x7fa6d57fa700 (LWP 29) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a758796958) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  16   Thread 0x7fa6d4ff9700 (LWP 30) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a7587969d8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  17   Thread 0x7fa6cbfff700 (LWP 31) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a758796a58) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  18   Thread 0x7fa6cb7fe700 (LWP 32) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a758796ad8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  19   Thread 0x7fa6caffd700 (LWP 33) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a758796b58) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  20   Thread 0x7fa6ca7fc700 (LWP 34) "redis-server" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  21   Thread 0x7fa6c9ffb700 (LWP 35) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a757ec72dc) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  22   Thread 0x7fa6c97fa700 (LWP 36) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a757ec735c) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  23   Thread 0x7fa6c8ff9700 (LWP 37) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a757ec73dc) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  24   Thread 0x7fa6c3fff700 (LWP 38) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a757ec745c) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  25   Thread 0x7fa6c37fe700 (LWP 39) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a757ec74d8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  26   Thread 0x7fa6c2ffd700 (LWP 40) "redis-server" futex_wait_cancelable (private=0, expected=0, futex_word=0x55a757ec755c) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  27   Thread 0x7fa6c27fc700 (LWP 41) "redis-server" __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
(gdb) thr 1
[Switching to thread 1 (Thread 0x7fa6eb593f80 (LWP 1))]
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
103	in ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S
(gdb) bt
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
#1  0x00007fa6eb763714 in __GI___pthread_mutex_lock (mutex=0x7ffda10b08d0) at ../nptl/pthread_mutex_lock.c:80
#2  0x00007fa6eb57f236 in RedisAI_ModelRun_RedisCommand () from /usr/lib/redis/modules/redisai.so
#3  0x000055a7571e66d6 in RedisModuleCommandDispatcher (c=0x7fa672ea81c0) at module.c:542
#4  0x000055a7571762b7 in call (c=0x7fa672ea81c0, flags=15) at server.c:2439
#5  0x000055a757176b5e in processCommand (c=0x7fa672ea81c0) at server.c:2733
#6  0x000055a757186d51 in processInputBuffer (c=0x7fa672ea81c0) at networking.c:1470
#7  0x000055a7571702e1 in aeProcessEvents (eventLoop=eventLoop@entry=0x7fa6eb03e0a0, flags=flags@entry=11) at ae.c:443
#8  0x000055a7571706eb in aeMain (eventLoop=0x7fa6eb03e0a0) at ae.c:501
#9  0x000055a75716d569 in main (argc=<optimized out>, argv=0x7ffda10b0c58) at server.c:4200
(gdb) thr 27
[Switching to thread 27 (Thread 0x7fa6c27fc700 (LWP 41))]
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
103	in ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S
(gdb) bt
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
#1  0x00007fa6eb763714 in __GI___pthread_mutex_lock (mutex=0x55a7572e7ca0 <moduleGIL>) at ../nptl/pthread_mutex_lock.c:80
#2  0x00007fa6eb5810bf in RedisAI_RunSession () from /usr/lib/redis/modules/redisai.so
#3  0x00007fa6eb581199 in RedisAI_Run_ThreadMain () from /usr/lib/redis/modules/redisai.so
#4  0x00007fa6eb760fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#5  0x00007fa6eb6914cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

@lantiga @MeirShpilraien it seems that our RedisAI_Run_ThreadMain is waiting on mutex 0x55a7572e7ca0 and RedisAI_ModelRun_RedisCommand is waiting on 0x7ffda10b08d0. 
I'll try one mutex approach

**Comment by filipecosta90** [comment]
a quick note:
to use gdb on redisai container I needed to run it in the following manner:
```
 docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -p 6379:6379 {IMAGE}
```
